name: Test Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: test pull request

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        cd ..
        git clone -b manim https://github.com/manim-kindergarten/manim_document_zh.git manim_with_doc
        cd manim_with_doc
        git clone https://github.com/manim-kindergarten/manim_sandbox.git
    
    - name: Install sphinx and manim env
      run: |
        pip3 install --upgrade pip
        sudo apt install python3-setuptools
        pip3 install -r requirements.txt
        pip3 install -r ../manim_with_doc/requirements.txt
    
    - name: Build document with Sphinx
      run: |
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/manim_document_zh/manim_with_doc"
        export SPHINXBUILD="python3 -m sphinx"
        make html

    - name: Build document for shaders
      run: |
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/manim_document_zh/manim_with_doc"
        export SPHINXBUILD="python3 -m sphinx"
        cd shaders
        make html